### PR TITLE
Add ethers wrapper

### PR DESCRIPTION
**Pull request by codfish**
Of note:

- need to pass uri to `getProvider` now

### CODE REVIEW

**Comment by willKim19** [comment]
Did you ever talk to the ethers people? I feel like we should talk to them before we do this.

**Comment by codfish** [comment]
@willKim19 yea, i was planning on reverting the changes **except** the addition of the ethers util file... thoughts?

**Comment by willKim19** [comment]
not exactly sure what you mean by that, reverting what changes?

**Comment by codfish** [comment]
@willKim19 like leaving web3-utils in place for the utility methods like `hexToUtf8` but just add the ethers wrapper to be able to maintain it in one place and use across projects

**Comment by willKim19** [comment]
okay

**Pull request merged**
